apiVersion: v1
kind: Service
metadata:
  name: {{ include "modelforge.fullname" . }}-ray-head
  labels:
    {{- include "modelforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: ray-head
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: client
    - port: 8265
      targetPort: 8265
      name: dashboard
    - port: 10001
      targetPort: 10001
      name: ray-client
  selector:
    app.kubernetes.io/name: {{ include "modelforge.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ray-head
